# Generated by Django 2.0.7 on 2019-01-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
