# Generated by Django 2.0.7 on 2019-01-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20190106_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='attachment',
            field=models.FileField(blank=True, upload_to='uploads/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('attention', 'Needs Attention'), ('research', 'Research')], max_length=100),
        ),
    ]
