# Generated by Django 2.0.7 on 2018-11-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20181120_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='ssn',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(max_length=30),
        ),
    ]
