# Generated by Django 2.0.7 on 2018-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20181126_1705'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='client',
    #         name='notes',
    #         field=models.CharField(max_length=400),
    #     ),
    
